name: Daily Video Check

on:
  schedule:
    - cron: '0 */2 * * *'  # Check every 2 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  check_and_post:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to commit changes to last_video_id.txt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run bot script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python bot.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add last_video_id.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update last processed video ID" && git push)
